# An example frontend web pod using Rails.

version: "2"

services:
  web:
    build: "https://github.com/andrewsardone/intro-graphql-talk-ruby.git"
    ports:
      - "3000:3000"
    labels:
      # The directory where our source code gets mounted into the container.
      io.fdy.cage.srcdir: "/usr/src/app"
      # Choose a more useful shell.
      io.fdy.cage.shell: "bash"
      # Our test command.  Invoke with `cage test frontend web`.
      io.fdy.cage.test: "bundle exec rake"
